[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[plugins]]
package = "netlify-plugin-html-validate"

  [plugins.inputs]
  # Исключаем все пути, содержащие node_modules
  exclude = ["**/node_modules/**"]
